### ISSUE TITLE
Hole Etching white line

### ISSUE THREAD

**Issue by TsuLab2023** [ViennaTools/ViennaPS#62]
When I simulate hole etching, there are some white line in paraview image (Material Ids).
I understand red is Si, blue is SiO2.
However, white is not mentioned in your code, so tell me what mean white line, please.

**Comment by TsuLab2023** [comment]
Thanks.
I understand what you mean by white lines.
In hole etching, why, depending on the conditions, is the hole's mask border jagged instead of straight?

**Comment by tobre1** [comment]
I'm not quite sure, I understand what you mean. It's possible that the Marching Cubes algorithm's mesh creation might not produce a perfectly defined line on the mask border due to limited spatial resolution. Have you observed variations in borders under different process conditions?
