### ISSUE TITLE
Wrong parameter specified for tests in README

### ISSUE THREAD

**Issue by Staudi14** [ViennaTools/ViennaPS#68]
In the README.md under tests the flag the command should read
```bash
cmake .. -DVIENNAPS_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=DEBUG
```
to be able to compile the tests.
Currently it reads:
```bash
cmake .. -DVIENNAPS_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=DEBUG
```

**Comment by tobre1** [comment]
Thank you for bringing this to our attention!

The typo has been fixed in the latest commit #69
