### ISSUE TITLE
Error while running example

### ISSUE THREAD

**Issue by 21cs053jay** [ViennaTools/ViennaPS#80]
When I try to run **atomicLayerDepostion** example from examples folder, i get an error message that says 

> lsDomain is redefined

, 

> lsVisualizationMesh is not defined 

and also error message of 

> no declaration of RTCIntersectContext

 shows up with them.

![ViennaPS error lsdomain](https://github.com/ViennaTools/ViennaPS/assets/110460429/fc077644-fc6b-495b-b2c0-0a9f4f2ff878)
![ViennaPS error lsWriteVisualisation](https://github.com/ViennaTools/ViennaPS/assets/110460429/515c8f76-5f9d-4427-9335-14e928686c66)
![image RTCIntersectContext](https://github.com/ViennaTools/ViennaPS/assets/110460429/775c4e87-a3d0-496e-b4ef-2e6041374c6d)

Please help if you can!

**Comment by tobre1** [comment]
It appears there are issues with your library setup. Could you provide details on how you configured the library and share the CMake output? This information will help diagnose the problem.

**Comment by 21cs053jay** [comment]
Yeah, so I used Visual Studio 17 as told in requirements and ran 

> cmake -B build

 command followed by

>  cmake --build build

 and 

> cmake --install build --prefix inst --config cfg

in visual studio's command prompt only.
But I am not sure where to find CMake output, could you please help a little?

**Comment by tobre1** [comment]
Unfortunately, I am not too familiar with the Windows build process since I only work on Linux and macOS. Maybe @Curve has an idea of what the problem could be here.

**Comment by Curve** [comment]
I could not reproduce this issue in a VM.

Your compile commands look off to me, please try again _(after deleting the build folder)_ with the following commands:

```bash
cmake -DVIENNAPS_BUILD_EXAMPLES=ON -B build
cmake --build build

# Optionally, if you want to install ViennaPS
cmake --install build

# Running the example is now as simple as (Debug should be replaced with the config specified, i.e. Release|Debug)
cd ./build/examples/atomicLayerDeposition/Debug/
./atomicLayerDeposition.bat ../config.txt
```

> Regarding your post detailing the build process:
> * `--config cfg`: `cfg` is not a valid build configuration. `Release` or `Debug` should be used, however, this option should not be required
> * `cmake --build build inst`: You don't need to build again after building initially. Also not sure why you specified `inst` here?

**Comment by 21cs053jay** [comment]
Can you explain a little more in detail about how to run an example? 
And I have built the files, should I install build or is it OK if I don't?

P.S: Thanks a lot mate, really grateful to you!!

**Comment by Curve** [comment]
> Can you explain a little more in detail about how to run an example? And I have built the files, should I install build or is it OK if I don't?
> 
> P.S: Thanks a lot mate, really grateful to you!!

In the code block I've posted I run the example at the bottom. All the examples are built into executables as usual, however, because every example requires certain VTK-Dependencies to be present it is recommended to run them via the `.bat` file that has the same name.

Installing is usually not required - It should only be used if you want to use ViennaPS as a system-wide library.

**Comment by 21cs053jay** [comment]
Yeah, so I used this command 
![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/76e525ce-b989-4952-b995-39969eb56b48)

but I am getting this error and also I can't find any .exe files or Path that is set inside .bat file.
![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/574185cd-011a-48e3-870f-fe5c8ec8a052)

**Comment by Curve** [comment]
Did you properly rebuild? Were there any issues during compilation?

Maybe the config defaulted to `Release` on your system, check if any executables are present in `build/examples/atomicLayerDeposition/Release`

**Comment by 21cs053jay** [comment]
My build completely without giving error: 
![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/ca48ce7f-8748-40c7-b510-fa0a36ad444f)
There are no executables in any of folder (i.e Debug/Release):
![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/c26adf47-ba9a-4f56-b24d-e7c962fe664f)

**Comment by Curve** [comment]
Did you also build? `cmake --build build`

**Comment by 21cs053jay** [comment]
No, I just ran the `cmake -DVIENNAPS_BUILD_EXAMPLES=ON -B build` command and then tried to install which generated this error
![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/93cc0f10-e26c-4d8f-9702-9664e44e7bf5)
 
and then you said it's unnecessary, so I left it. and nothing else.

**Comment by Curve** [comment]
I said installing is not necessary. Not building...

**Comment by 21cs053jay** [comment]
I thought this command cmake --install build is used for installing it, didn't knew that it is part of build.

Can you please look at the error in the above comment?

**Comment by Curve** [comment]
> I thought this command cmake --install build is used for installing it, didn't knew that it is part of build.
> 
> Can you please look at the error in the above comment?

CMake Install is used to install it on the system.

CMake build is used to **actually build the libraries and executabes**.

The error in your screenshots occurs because you didn't build anything...

**Comment by 21cs053jay** [comment]
So I started cmake --build build command, and it gave me this error:
![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/2daea455-6373-4e6b-b26b-45ff948a5b91)

**Comment by Curve** [comment]
> So I started cmake --build build command, and it gave me this error: ![image](https://private-user-images.githubusercontent.com/110460429/332525404-2daea455-6373-4e6b-b26b-45ff948a5b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTU2NDUsIm5iZiI6MTcxNjMxNTM0NSwicGF0aCI6Ii8xMTA0NjA0MjkvMzMyNTI1NDA0LTJkYWVhNDU1LTYzNzMtNGU2Yi1iMjZiLTQ1ZmY5NDhhNWI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxODE1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzcwYTlhZTE4YzliZDAxNTI4YzViOTg0YTM0ZTU5MWNkNTJiMjNiNjlhYmZhZmM3ZjQwY2UzYTZkNjRkZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rHbQCxm_P_tyVN8sEek2fLGkMu_zLJFqwq7Dn__mkUY)

Looks like an issue with OpenMP. Try updating your compiler (Visual Studio in this case) to a more recent version

**Comment by Curve** [comment]
> I tried updating my OpenMP and then again ran the `cmake --build build` command and got these errors now which shows that pre-defined library files have problematic lines, what should I do now?
> 
> ![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/3a827d9b-c45c-4131-8a88-4ece77c02f92)
> 
> Are there any fixes available?
> Should I move to specific versions, if yes then which versions of those?
> 

Build with Visual Studio instead of MinGW

**Comment by 21cs053jay** [comment]
Yeah, so I used Visual Studio 17 2022 Win64 as generator but still I am getting this error while I build it.

![image](https://github.com/ViennaTools/ViennaPS/assets/110460429/01a02434-1c6e-421f-931b-da1cea9e9713)

Can you please help me through it?
