### ISSUE TITLE
Material check for deposition

### ISSUE THREAD

**Issue by kenyastyle** [ViennaTools/ViennaPS#94]
https://github.com/ViennaTools/ViennaPS/blob/37b5c3486eb54f85e3bd0d348826abc1f497dcfc/include/viennaps/models/psIsotropicProcess.hpp#L29

In the isotropic model, rate is 0 if mask. However, this should only be the case if etching. When depositing, the rate should be the same regardless of material.

**Comment by tobre1** [comment]
In the Python wrapper, per default, the Material.Mask is added as mask material. This should be fixed to add no default mask material. 

- [ ] Change default mask material in istropic process model Python wrapper
